export enum TipoReferencia{

    INGRESO = 'INGRESO',
    EGRESO = 'EGRESO',
    ORDEN = 'ORDEN',

    AJUSTE_UPDATE_EGRESO = 'AJUSTE_UPDATE_EGRESO',
    AJUSTE_UPDATE_INGRESO = 'AJUSTE_UPDATE_INGRESO',
    AJUSTE_DELETE_EGRESO = 'AJUSTE_DELETE_EGRESO',
    AJUSTE_DELETE_INGRESO = 'AJUSTE_DELETE_INGRESO',
    AJUSTE_MANUAL = 'AJUSTE_MANUAL'

}