server {

    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;

    index index.html;

    # Evita que Nginx genere redirects absolutos
    # como http://localhost/login/
    absolute_redirect off;


    location / {

        # Primero busca el index prerenderizado de Angular.
        # Así /login resuelve directamente login/index.html
        # y no intenta redirigir al directorio /login/
        try_files $uri/index.html $uri /index.html;

    }

}